/**
 * Initial state for the game reducer.
 */

import type { GameState } from './types';
import { createEmptyGrid } from './helpers';
import {
  DEFAULT_LEVELS,
  INITIAL_TOOL_MODE,
  DEFAULT_FARM_COLS,
  DEFAULT_FARM_ROWS,
  DEFAULT_HOUSE_COLS,
  DEFAULT_HOUSE_ROWS,
} from './constants';

/** Default state when the game context mounts (before snapshot). */
export const initialState: GameState = {
  activeScene: 'farm',
  farmGrid: createEmptyGrid(DEFAULT_FARM_COLS, DEFAULT_FARM_ROWS),
  houseGrid: createEmptyGrid(DEFAULT_HOUSE_COLS, DEFAULT_HOUSE_ROWS),
  selectedTile: null,
  selectedItemType: null,
  isTransitioning: false,
  editMode: false,
  activeCategory: 'all',
  inventory: {},
  storage: {},
  backpackSlots: 20,
  miningEnergy: 20,
  miningEnergyCap: 20,
  miningEnergyAt: 0,
  harvestEffects: [],
  farmName: 'My Farm',
  farmXp: 0,
  farmLevel: 1,
  farmLevels: DEFAULT_LEVELS,
  equipped: undefined,
  foodDishQueues: undefined,
  itemDefs: {},
  sceneryUrl: '',
  pendingInteraction: null,
  movingItemId: null,
  pendingDropTarget: null,
  pendingPlacements: [],
  toolMode: INITIAL_TOOL_MODE,
  gems: 0,
  activeBugs: [],
  lastCatchResult: null,
  activeBalloons: [],
  lastBalloonPopResult: null,
  lastFossilDigResult: null,
  quests: [],
  canUpgrade: false,
  dialogQueue: [],
  currentDialog: null,
  questDialogIndex: 0,
  questCompletions: [],
  shopOpen: false,
  sellBoxOpen: false,
  cookingOpen: false,
  craftingOpen: false,
  foodDishOpen: false,
  equipOpen: false,
  petBehaviorSync: null,
  petState: null,
  pendingSellItems: null,
  pendingSellAt: null,
  shakingTreeAnchorId: null,
  shakeTrigger: 0,
  weather: { type: 'clear', date: '' },
  weatherOverride: null,
};
