/**
 * Theme-aware styles for the Game HUD.
 */

import { StyleSheet, Platform } from 'react-native';
import type { AppTheme } from '@/constants/theme';
import { HUD_PILL_HEIGHT } from './constants';

export function createHudStyles(colors: AppTheme['colors'], screenWidth: number) {
  return StyleSheet.create({
    container: { ...StyleSheet.absoluteFillObject, zIndex: 200 },
    topRow: {
      position: 'absolute',
      left: 12,
      right: 12,
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    leftColumn: { flexDirection: 'column', alignItems: 'flex-start', gap: 4 },
    topLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    pill: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: HUD_PILL_HEIGHT,
      backgroundColor: colors.surface + 'E6',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 16,
      gap: 6,
      ...(Platform.select({
        ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
        android: { elevation: 3 },
      }) as object),
    },
    pillEmoji: { fontSize: 16 },
    pillText: { fontSize: 13, fontWeight: '700' as const, color: colors.text, letterSpacing: 0.3 },
    pillSep: {
      width: 1,
      height: 14,
      backgroundColor: colors.border,
      marginHorizontal: 2,
    },
    gemEmoji: { fontSize: 14 },
    gemCount: { fontSize: 13, fontWeight: '800' as const, color: colors.gemColor ?? colors.accent, letterSpacing: 0.3 },
    lvlBadge: {
      backgroundColor: colors.primary,
      paddingHorizontal: 6,
      paddingVertical: 1,
      borderRadius: 8,
      marginLeft: 2,
    },
    lvlText: { fontSize: 10, fontWeight: '800' as const, color: colors.onPrimary ?? '#fff' },
    upgradeDot: {
      position: 'absolute' as const,
      top: -2,
      right: -2,
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: '#F59E0B',
      borderWidth: 1.5,
      borderColor: colors.surface,
    },
    highlightWrap: { borderRadius: 14 },
    highlightBorder: { borderWidth: 2, borderColor: '#FFD700' },
    /** Explicitly zeros border/glow when a quest highlight is removed. */
    highlightClear: {
      shadowColor: 'transparent',
      shadowOpacity: 0,
      shadowRadius: 0,
      shadowOffset: { width: 0, height: 0 },
      elevation: 0,
      borderWidth: 0,
      borderColor: 'transparent',
    },
    moveBanner: { position: 'absolute' as const, left: 12, right: 12, alignItems: 'center' },
    moveBannerInner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.primary + 'EB',
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 16,
      ...(Platform.select({
        ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
        android: { elevation: 3 },
      }) as object),
    },
    moveBannerText: {
      fontSize: 13,
      fontWeight: '700' as const,
      color: colors.onPrimary ?? '#fff',
      flex: 1,
    },
    moveCancelBtn: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 10,
      backgroundColor: (colors.onPrimary ?? '#fff') + '40',
    },
    moveCancelText: {
      fontSize: 12,
      fontWeight: '700' as const,
      color: colors.onPrimary ?? '#fff',
    },
    toolbarWrap: {
      position: 'absolute' as const,
      left: 0,
      right: 0,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 210,
    },
    toolbar: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.surface + 'EB',
      borderRadius: 24,
      paddingHorizontal: 6,
      paddingVertical: 6,
      ...(Platform.select({
        ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
        android: { elevation: 3 },
      }) as object),
    },
    toolBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    backpackBadge: {
      position: 'absolute' as const,
      right: -6,
      bottom: -4,
      minWidth: 28,
      paddingHorizontal: 4,
      paddingVertical: 1,
      borderRadius: 8,
      borderWidth: 1.5,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    backpackBadgeText: {
      fontSize: 8,
      fontWeight: '800' as const,
      fontVariant: ['tabular-nums'] as const,
      letterSpacing: -0.2,
    },
    toolSep: {
      width: 1,
      height: 24,
      backgroundColor: colors.border,
    },
    trashRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    buildPalette: {
      position: 'absolute' as const,
      left: 12,
      right: 12,
      zIndex: 205,
    },
    buildPaletteInner: {
      backgroundColor: colors.surface + 'F2',
      borderRadius: 20,
      paddingVertical: 12,
      paddingHorizontal: 12,
      gap: 12,
      ...(Platform.select({
        ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
        android: { elevation: 3 },
      }) as object),
    },
    buildChipRowWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 4,
    },
    buildChipScroll: { flex: 1, minWidth: 0 },
    buildChipScrollContent: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingRight: 16,
    },
    buildChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 14,
      backgroundColor: colors.border + '80',
    },
    buildChipActive: { backgroundColor: colors.primary },
    expandChip: { backgroundColor: colors.border + '99', flexShrink: 0 },
    expandChipActive: { backgroundColor: colors.primary },
    buildChipText: { fontSize: 13, fontWeight: '700' as const, color: colors.textSecondary },
    buildChipTextActive: { color: colors.onPrimary ?? '#fff' },
    buildSlotScroll: { overflow: 'hidden' as const },
    buildSlotRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      paddingHorizontal: 4,
    },
    buildSlotRowWrap: {
      flexWrap: 'wrap' as const,
      alignContent: 'flex-start' as const,
      width: Math.max(screenWidth - 40, 320),
    },
    buildSlot: {
      width: 64,
      alignItems: 'center',
      paddingVertical: 6,
      paddingHorizontal: 4,
      borderRadius: 14,
      borderWidth: 2,
      borderColor: 'transparent',
      backgroundColor: colors.border + '66',
    },
    buildSlotActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primary + '1F',
    },
    buildSlotInert: { opacity: 0.7 },
    buildSlotIconWrap: {
      position: 'relative' as const,
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 4,
    },
    buildSlotImage: { width: 36, height: 36 },
    buildSlotEmoji: { fontSize: 22 },
    buildQtyBadge: {
      position: 'absolute' as const,
      top: -4,
      right: -4,
      minWidth: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: colors.border + '9E',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 4,
    },
    buildQtyBadgeActive: { backgroundColor: colors.primary },
    buildQtyText: { fontSize: 10, fontWeight: '800' as const, color: colors.textMuted },
    buildQtyTextActive: { color: colors.onPrimary ?? '#fff' },
    buildSlotLabel: {
      fontSize: 10,
      fontWeight: '600' as const,
      color: colors.textSecondary,
      textAlign: 'center' as const,
    },
    buildSlotLabelActive: { color: colors.primary },
    buildEmptyHint: {
      fontSize: 13,
      color: colors.textMuted,
      paddingVertical: 12,
      paddingHorizontal: 24,
    },
  });
}
